# ä¸ç”¨åœ¨æç¤ºç¬¦å‰æ¢è¡Œ
add_newline = false

# å½“ starship æ‰«æå½“å‰ç›®å½•ä¸‹çš„æ–‡ä»¶å’Œæ–‡ä»¶å¤¹æ—¶ï¼Œæœ€å¤šä½¿ç”¨ 10 æ¯«ç§’
scan_timeout = 10


[cmd_duration]
min_time = 500

[directory]
truncation_length = 3

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 100
truncation_symbol = "..."

[hostname]
ssh_only = true
disabled = false

