# ä¸ç”¨åœ¨æç¤ºç¬¦å‰æ¢è¡Œ
add_newline = false

# ä½¿ç”¨è‡ªå®šä¹‰çš„ç»„ä»¶é¡ºåºæ›¿æ¢é»˜è®¤ç»„ä»¶é¡ºåº
prompt_order=["hostname","ruby","nodejs","git_branch","git_status","cmd_duration","line_break","directory","character"]

# å½“ starship æ‰«æå½“å‰ç›®å½•ä¸‹çš„æ–‡ä»¶å’Œæ–‡ä»¶å¤¹æ—¶ï¼Œæœ€å¤šä½¿ç”¨ 10 æ¯«ç§’
scan_timeout = 10


[cmd_duration]
min_time = 500
prefix = "executed times "

[directory]
truncation_length = 3

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 100
truncation_symbol = "..."

[hostname]
ssh_only = true
prefix = "âŸª"
suffix = "âŸ«"
disabled = false

